version: '3.8'

services:
  backend:
    build: ./backend
    container_name: blog-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend/database.db:/app/database.db
      - /var/www/myweb/posts:/public/posts
      - /var/www/myweb/tags:/public/tags
      - /var/www/myweb/blogroll:/public/blogroll
      - /var/www/myweb/profile.json:/public/profile.json
    env_file:
      - ./backend/.env
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
